# Generated by Django 4.1 on 2022-08-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=40)),
                ('api_url', models.CharField(blank=True, help_text='ex: http://localhost:8000/api', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROCESS', 'In Process'), ('STORED', 'Stored'), ('SEND', 'Send')], default='NEW', max_length=255)),
                ('store_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.storeaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
